version: 0.2
phases:
    build:
        commands:            
            - dotnet new -i Amazon.Lambda.Templates::*
            - cd AWSLambda2
            - (Get-Item -Path ".\" -Verbose).FullName
            - dotnet restore
            - dotnet lambda package
            
artifacts:
  files:
    - /bin/release/netcoreapp2.0/AWSLambda2.zip
    - deployment-template.yml