version: 0.2
phases:
    build:
        commands:                        
            - cd AWSLambda2            
            - dotnet restore
            - dotnet lambda package -c Release -o ../Package.zip            
            - aws cloudformation package --template ../deployment-template.yml --s3-bucket $S3_BUCKET --output-template ../deployment-template.yml
artifacts:
  files:    
    - deployment-template.yml